[package]
name = "postgres-conn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
secstr = "0.5.0"
pretty_env_logger = "0.4.0"
clap = { version = "3.2.7", features = ["derive"] }
